AWSTemplateFormatVersion: 2010-09-09
Description: Testing Cloudformation

Parameters:
  Customer:
    Type: String
  Owner:
    Type: String

############################
# Cloudformation Resources #
############################

Resources:
  devVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.240.0.0/22
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub dev-vpc-${Customer}
        - Key: Purpose
          Value: dev
        - Key: Owner
          Value: !Ref Owner